[project]
name = "autogen-afac2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autogen-agentchat>=0.5.7",
    "autogen-ext[diskcache]>=0.5.7",
    "autogenstudio>=0.4.2.2",
    "pyautogen>=0.9",
]
